export const orderDto = (order: any, rider?: { name?: string; phone?: string } | null) => ({
  id: order._id.toString(),
  orderNumber: order.orderNumber,
  customerId: order.customerId.toString(),
  restaurantId: order.restaurantId.toString(),
  restaurantName: order.restaurantName,
  items: order.items,
  deliveryAddress: order.deliveryAddress,
  subtotal: order.subtotal,
  deliveryFee: order.deliveryFee,
  discount: order.discount,
  total: order.total,
  couponCode: order.couponCode,
  note: order.note ?? "",
  paymentMethod: order.paymentMethod,
  paymentStatus: order.paymentStatus,
  status: order.status,
  statusHistory: order.statusHistory,
  estimatedDeliveryAt: order.estimatedDeliveryAt,
  riderId: order.riderId?.toString?.() ?? order.riderId ?? undefined,
  riderName: rider?.name ?? undefined,
  riderPhone: rider?.phone ?? undefined,
  deliveryOtp: order.deliveryOtp ?? undefined,
  deliveryVerified: order.deliveryVerified ?? false,
  createdAt: order.createdAt,
});
